// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SGT_BRIDGE.Models;

public partial class dok__Dokument
{
    public int dok_Id { get; set; }

    public int dok_Typ { get; set; }

    public int dok_Podtyp { get; set; }

    public int? dok_MagId { get; set; }

    public int? dok_Nr { get; set; }

    public string dok_NrRoz { get; set; }

    public string dok_NrPelny { get; set; }

    public string dok_NrPelnyOryg { get; set; }

    public int? dok_DoDokId { get; set; }

    public string dok_DoDokNrPelny { get; set; }

    public DateTime? dok_DoDokDataWyst { get; set; }

    public string dok_MscWyst { get; set; }

    public DateTime dok_DataWyst { get; set; }

    public DateTime dok_DataMag { get; set; }

    public DateTime? dok_DataOtrzym { get; set; }

    public int? dok_PlatnikId { get; set; }

    public int? dok_PlatnikAdreshId { get; set; }

    public int? dok_OdbiorcaId { get; set; }

    public int? dok_OdbiorcaAdreshId { get; set; }

    public int? dok_PlatId { get; set; }

    public DateTime? dok_PlatTermin { get; set; }

    public string dok_Wystawil { get; set; }

    public string dok_Odebral { get; set; }

    public int? dok_PersonelId { get; set; }

    public int? dok_CenyPoziom { get; set; }

    public int? dok_CenyTyp { get; set; }

    public decimal? dok_CenyKurs { get; set; }

    public decimal dok_CenyNarzut { get; set; }

    public decimal dok_RabatProc { get; set; }

    public decimal dok_WartUsNetto { get; set; }

    public decimal dok_WartUsBrutto { get; set; }

    public decimal dok_WartTwNetto { get; set; }

    public decimal dok_WartTwBrutto { get; set; }

    public decimal dok_WartOpZwr { get; set; }

    public decimal dok_WartOpWyd { get; set; }

    public decimal dok_WartMag { get; set; }

    public decimal dok_WartMagP { get; set; }

    public decimal dok_WartMagR { get; set; }

    public decimal dok_WartNetto { get; set; }

    public decimal dok_WartVat { get; set; }

    public decimal dok_WartBrutto { get; set; }

    public decimal? dok_KwWartosc { get; set; }

    public decimal? dok_KwGotowka { get; set; }

    public decimal? dok_KwKarta { get; set; }

    public decimal? dok_KwDoZaplaty { get; set; }

    public decimal? dok_KwKredyt { get; set; }

    public decimal? dok_KwReszta { get; set; }

    public string dok_Waluta { get; set; }

    public decimal dok_WalutaKurs { get; set; }

    public string dok_Uwagi { get; set; }

    public int? dok_KatId { get; set; }

    public string dok_Tytul { get; set; }

    public string dok_Podtytul { get; set; }

    public int dok_Status { get; set; }

    public int dok_StatusKsieg { get; set; }

    public int dok_StatusFiskal { get; set; }

    public bool dok_StatusBlok { get; set; }

    public bool dok_JestTylkoDoOdczytu { get; set; }

    public bool dok_JestRuchMag { get; set; }

    public bool dok_JestZmianaDatyDokKas { get; set; }

    public bool dok_JestHOP { get; set; }

    public bool dok_JestVatNaEksport { get; set; }

    public bool dok_JestVatAuto { get; set; }

    public int dok_Algorytm { get; set; }

    public int? dok_KartaId { get; set; }

    public int? dok_KredytId { get; set; }

    public int dok_RodzajOperacjiVat { get; set; }

    public int? dok_KodRodzajuTransakcji { get; set; }

    public int? dok_StatusEx { get; set; }

    public int? dok_ObiektGT { get; set; }

    public bool dok_Rozliczony { get; set; }

    public int? dok_RejId { get; set; }

    public DateTime? dok_TerminRealizacji { get; set; }

    public int dok_WalutaLiczbaJednostek { get; set; }

    public int? dok_WalutaRodzajKursu { get; set; }

    public DateTime? dok_WalutaDataKursu { get; set; }

    public int? dok_WalutaIdBanku { get; set; }

    public int dok_CenyLiczbaJednostek { get; set; }

    public int? dok_CenyRodzajKursu { get; set; }

    public DateTime? dok_CenyDataKursu { get; set; }

    public int? dok_CenyIdBanku { get; set; }

    public decimal? dok_KwPrzelew { get; set; }

    public decimal? dok_KwGotowkaPrzedplata { get; set; }

    public decimal? dok_KwPrzelewPrzedplata { get; set; }

    public int? dok_DefiniowalnyId { get; set; }

    public int? dok_TransakcjaId { get; set; }

    public string dok_TransakcjaSymbol { get; set; }

    public DateTime? dok_TransakcjaData { get; set; }

    public int? dok_PodsumaVatFSzk { get; set; }

    public int? dok_ZlecenieId { get; set; }

    public bool dok_NaliczajFundusze { get; set; }

    public bool? dok_PrzetworzonoZKwZD { get; set; }

    public bool? dok_VatMarza { get; set; }

    public int? dok_DstNr { get; set; }

    public string dok_DstNrRoz { get; set; }

    public string dok_DstNrPelny { get; set; }

    public int? dok_ObslugaDokDost { get; set; }

    public int? dok_AkcyzaZwolnienieId { get; set; }

    public int dok_ProceduraMarzy { get; set; }

    public bool dok_FakturaUproszczona { get; set; }

    public DateTime? dok_DataZakonczenia { get; set; }

    public bool dok_MetodaKasowa { get; set; }

    public int dok_TypNrIdentNabywcy { get; set; }

    public string dok_NrIdentNabywcy { get; set; }

    public int? dok_AdresDostawyId { get; set; }

    public int? dok_AdresDostawyAdreshId { get; set; }

    public int? dok_VenderoId { get; set; }

    public string dok_VenderoSymbol { get; set; }

    public DateTime? dok_VenderoData { get; set; }

    public int? dok_SelloId { get; set; }

    public string dok_SelloSymbol { get; set; }

    public DateTime? dok_SelloData { get; set; }

    public int? dok_TransakcjaJednolitaId { get; set; }

    public bool? dok_PodpisanoElektronicznie { get; set; }

    public string dok_UwagiExt { get; set; }

    public int? dok_VenderoStatus { get; set; }

    public bool? dok_ZaimportowanoDoEwidencjiAkcyzowej { get; set; }

    public int? dok_TermPlatStatus { get; set; }

    public string dok_TermPlatTransId { get; set; }

    public bool dok_DokumentFiskalnyDlaPodatnikaVat { get; set; }

    public bool dok_CesjaPlatnikOdbiorca { get; set; }

    public decimal dok_WartOplRecykl { get; set; }

    public int? dok_TermPlatIdKonfig { get; set; }

    public int? dok_TermPlatIdZadania { get; set; }

    public int? dok_PromoZenCardStatus { get; set; }

    public int? dok_NrRachunkuBankowegoPdm { get; set; }

    public bool dok_SzybkaPlatnosc { get; set; }

    public bool dok_MechanizmPodzielonejPlatnosci { get; set; }

    public int? dok_IdSesjiKasowej { get; set; }

    public decimal? dok_KwKartaPrzedplata { get; set; }

    public int? dok_IdPanstwaRozpoczeciaWysylki { get; set; }

    public int? dok_IdPanstwaKonsumenta { get; set; }

    public string dok_InformacjeDodatkowe { get; set; }

    public bool dok_ZnacznikiGTUNaPozycji { get; set; }

    public int? dok_TypDatyUjeciaKorekty { get; set; }

    public DateTime? dok_DataUjeciaKorekty { get; set; }

    public int? dok_IdPrzyczynyZwolnieniaZVAT { get; set; }

    public string dok_NumerKSeF { get; set; }

    public DateTime? dok_DataNumeruKSeF { get; set; }

    public string dok_DoNumerKSeF { get; set; }

    public int? dok_KodRodzajuTransportu { get; set; }

    public string dok_DodatkoweInfoRodzajuTransportu { get; set; }

    public string dok_CzasWysylkiTransportu { get; set; }

    public string dok_CzasPrzewozuTransportu { get; set; }

    public int dok_StatusKSeF { get; set; }

    public bool dok_KorektaDanychNabywcy { get; set; }

    public string dok_WegielNumerOswiadczenia { get; set; }

    public string dok_SesjaKSeF { get; set; }

    public string dok_IdPrzetwarzaniaKSeF { get; set; }

    public int? dok_SrodowiskoKSeF { get; set; }

    public string dok_BladKSeF { get; set; }

    public DateTime? dok_DataRozpoczeciaPrzetwarzaniaKSeF { get; set; }

    public string dok_XmlHashKSeF { get; set; }

    public string dok_TermPlatTerminalId { get; set; }

    public string dok_FiskalizacjaNumer { get; set; }

    public DateTime? dok_FiskalizacjaData { get; set; }

    public string dok_FiskalizacjaIdUrzadzenia { get; set; }

    public DateTime? dok_DataWystawieniaKSeF { get; set; }

    public int dok_FormaDokumentowania { get; set; }

    public bool dok_CzekaNaKSeF { get; set; }

    public bool dok_VatRozliczanyPrzezUslugobiorce { get; set; }

    public bool dok_PodlegaOplSpec { get; set; }

    public string dok_DataNumeruKSeFOryg { get; set; }

    public int dok_RolaOdbiorcyKSeF { get; set; }

    public int? dok_VatMetodaLiczenia { get; set; }

    public DateTime? dok_TerminWysylkiDoKSeF { get; set; }

    public bool? dok_ZrealizowaneZRezerwacja { get; set; }

    public virtual sl_Panstwo dok_IdPanstwaKonsumentaNavigation { get; set; }

    public virtual sl_Panstwo dok_IdPanstwaRozpoczeciaWysylkiNavigation { get; set; }
}