// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SGT_BRIDGE.Models;

public partial class LEO_SystemRabatowy_ZestawyPowiazania
{
    public int zrp_Id { get; set; }

    public int? zrp_Typ { get; set; }

    public int? zrp_ZestawId { get; set; }

    public int? zrp_ObiektId { get; set; }

    public decimal? zrp_Wartosc { get; set; }

    public decimal? zrp_Wartosc2 { get; set; }
}