// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SGT_BRIDGE.Models;

public partial class sl_Panstwo
{
    public int pa_Id { get; set; }

    public string pa_Nazwa { get; set; }

    public string pa_KodPanstwaUE { get; set; }

    public bool pa_CzlonekUE { get; set; }

    public string pa_KodPanstwaISO { get; set; }

    public virtual ICollection<dok__Dokument> dok__Dokumentdok_IdPanstwaKonsumentaNavigation { get; set; } = new List<dok__Dokument>();

    public virtual ICollection<dok__Dokument> dok__Dokumentdok_IdPanstwaRozpoczeciaWysylkiNavigation { get; set; } = new List<dok__Dokument>();
}