// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace SGT_BRIDGE.Models;

public partial class SubiektGTDbContext : DbContext
{
    public SubiektGTDbContext()
    {
    }

    public SubiektGTDbContext(DbContextOptions<SubiektGTDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<LEO_SystemRabatowy_Zbiorcze> LEO_SystemRabatowy_Zbiorcze { get; set; }

    public virtual DbSet<LEO_SystemRabatowy_Zestawy> LEO_SystemRabatowy_Zestawy { get; set; }

    public virtual DbSet<LEO_SystemRabatowy_ZestawyGrupyKh> LEO_SystemRabatowy_ZestawyGrupyKh { get; set; }

    public virtual DbSet<LEO_SystemRabatowy_ZestawyKontrahenci> LEO_SystemRabatowy_ZestawyKontrahenci { get; set; }

    public virtual DbSet<LEO_SystemRabatowy_ZestawyMagazyny> LEO_SystemRabatowy_ZestawyMagazyny { get; set; }

    public virtual DbSet<LEO_SystemRabatowy_ZestawyPowiazania> LEO_SystemRabatowy_ZestawyPowiazania { get; set; }

    public virtual DbSet<sl_Magazyn> sl_Magazyn { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=(local)\\PROD;Initial Catalog=MEGSTYL;Integrated Security=True;Encrypt=True;Trust Server Certificate=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<LEO_SystemRabatowy_Zbiorcze>(entity =>
        {
            entity.HasNoKey();

            entity.HasIndex(e => new { e.zb_Typ, e.zb_ObiektId }, "IDX_ZZ").IsUnique();

            entity.Property(e => e.zb_Wartosc).HasColumnType("decimal(10, 2)");
        });

        modelBuilder.Entity<LEO_SystemRabatowy_Zestawy>(entity =>
        {
            entity.HasKey(e => e.zr_Id).HasName("PK__LEO_Syst__FB4BF42D1D0EF822");

            entity.HasIndex(e => e.zr_Symbol, "SymbolUnique").IsUnique();

            entity.Property(e => e.zr_DataDo).HasColumnType("datetime");
            entity.Property(e => e.zr_DataOd).HasColumnType("datetime");
            entity.Property(e => e.zr_DodatkowyRabatUpustKwotowyZestaw).HasDefaultValue(true);
            entity.Property(e => e.zr_DodatkowyRabatUpustProcentowyZestaw).HasDefaultValue(true);
            entity.Property(e => e.zr_Nazwa)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.zr_Notatki).HasColumnType("text");
            entity.Property(e => e.zr_OstatniaModyfikacja).HasColumnType("datetime");
            entity.Property(e => e.zr_Symbol)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasDefaultValue("brak");
        });

        modelBuilder.Entity<LEO_SystemRabatowy_ZestawyGrupyKh>(entity =>
        {
            entity.HasNoKey();

            entity.HasIndex(e => new { e.zrg_ZestawId, e.zrg_GrupaId }, "IDX_ZGK")
                .IsUnique()
                .IsClustered();
        });

        modelBuilder.Entity<LEO_SystemRabatowy_ZestawyKontrahenci>(entity =>
        {
            entity.HasKey(x => new { x.zrk_ZestawId, x.zrk_KontrahentId });

            entity.HasIndex(e => new { e.zrk_ZestawId, e.zrk_KontrahentId }, "IDX_ZK")
                .IsUnique()
                .IsClustered();
        });

        modelBuilder.Entity<LEO_SystemRabatowy_ZestawyMagazyny>(entity =>
        {
            entity.HasKey(x => new { x.zrm_MagazynId, x.zrm_ZestawId });

            entity.HasIndex(e => new { e.zrm_ZestawId, e.zrm_MagazynId }, "IDX_ZM")
                .IsUnique()
                .IsClustered();
        });

        modelBuilder.Entity<LEO_SystemRabatowy_ZestawyPowiazania>(entity =>
        {
            entity.HasKey(e => e.zrp_Id).HasName("PK__LEO_Syst__1F060F0FFD51D672");

            entity.HasIndex(e => new { e.zrp_Typ, e.zrp_ZestawId, e.zrp_ObiektId }, "IDX_ZP").IsUnique();

            entity.Property(e => e.zrp_Wartosc).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.zrp_Wartosc2).HasColumnType("decimal(10, 2)");
        });

        modelBuilder.Entity<sl_Magazyn>(entity =>
        {
            entity.HasKey(e => e.mag_Id);

            entity.ToTable(tb =>
                {
                    tb.HasTrigger("tr_MagazynInsMod");
                    tb.HasTrigger("tr_slMagazynInserting");
                    tb.HasTrigger("tr_sl_Magazyn_Deleting");
                });

            entity.Property(e => e.mag_Id).ValueGeneratedNever();
            entity.Property(e => e.mag_Analityka)
                .HasMaxLength(5)
                .IsUnicode(false);
            entity.Property(e => e.mag_Nazwa)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.mag_Opis)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.mag_POSAdres)
                .HasMaxLength(82)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.mag_POSNazwa)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.mag_Status).HasDefaultValue(1);
            entity.Property(e => e.mag_Symbol)
                .IsRequired()
                .HasMaxLength(3)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}