// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SGT_BRIDGE.Models;

public partial class twi_TowarIndeks
{
    public int twi_Id { get; set; }

    public string twi_1 { get; set; }

    public string twi_2 { get; set; }

    public string twi_3 { get; set; }

    public string twi_4 { get; set; }

    public string twi_5 { get; set; }

    public string twi_6 { get; set; }

    public string twi_7 { get; set; }

    public string twi_8 { get; set; }

    public string twi_9 { get; set; }

    public string twi_10 { get; set; }

    public string twi_11 { get; set; }

    public string twi_12 { get; set; }

    public string twi_13 { get; set; }

    public string twi_14 { get; set; }

    public string twi_15 { get; set; }

    public string twi_16 { get; set; }

    public string twi_17 { get; set; }

    public string twi_18 { get; set; }

    public string twi_19 { get; set; }

    public string twi_20 { get; set; }

    public string twi_21 { get; set; }

    public string twi_22 { get; set; }

    public string twi_23 { get; set; }

    public string twi_24 { get; set; }

    public string twi_25 { get; set; }

    public string twi_26 { get; set; }

    public string twi_27 { get; set; }

    public string twi_28 { get; set; }

    public string twi_29 { get; set; }

    public string twi_30 { get; set; }

    public string twi_31 { get; set; }

    public string twi_32 { get; set; }

    public string twi_33 { get; set; }

    public string twi_34 { get; set; }

    public string twi_35 { get; set; }

    public string twi_36 { get; set; }

    public string twi_37 { get; set; }

    public string twi_38 { get; set; }

    public string twi_39 { get; set; }

    public string twi_40 { get; set; }

    public string twi_41 { get; set; }

    public string twi_42 { get; set; }

    public string twi_43 { get; set; }

    public string twi_44 { get; set; }

    public string twi_45 { get; set; }

    public string twi_46 { get; set; }

    public string twi_47 { get; set; }

    public string twi_48 { get; set; }

    public string twi_49 { get; set; }

    public string twi_50 { get; set; }

    public string twi_51 { get; set; }

    public string twi_52 { get; set; }

    public string twi_53 { get; set; }

    public string twi_54 { get; set; }

    public string twi_55 { get; set; }

    public string twi_56 { get; set; }

    public string twi_57 { get; set; }

    public string twi_58 { get; set; }

    public string twi_59 { get; set; }

    public string twi_60 { get; set; }

    public string twi_61 { get; set; }

    public string twi_62 { get; set; }

    public string twi_63 { get; set; }

    public string twi_64 { get; set; }

    public string twi_65 { get; set; }

    public string twi_66 { get; set; }

    public string twi_67 { get; set; }

    public string twi_68 { get; set; }

    public string twi_69 { get; set; }

    public string twi_70 { get; set; }

    public string twi_71 { get; set; }

    public string twi_72 { get; set; }

    public string twi_73 { get; set; }

    public string twi_74 { get; set; }

    public string twi_75 { get; set; }

    public string twi_76 { get; set; }

    public string twi_77 { get; set; }

    public string twi_78 { get; set; }

    public string twi_79 { get; set; }

    public string twi_80 { get; set; }

    public string twi_81 { get; set; }

    public string twi_82 { get; set; }

    public string twi_83 { get; set; }

    public string twi_84 { get; set; }

    public string twi_85 { get; set; }

    public string twi_86 { get; set; }

    public string twi_87 { get; set; }

    public string twi_88 { get; set; }

    public string twi_89 { get; set; }

    public string twi_90 { get; set; }

    public string twi_91 { get; set; }

    public string twi_92 { get; set; }

    public string twi_93 { get; set; }

    public string twi_94 { get; set; }

    public string twi_95 { get; set; }

    public string twi_96 { get; set; }

    public string twi_97 { get; set; }

    public string twi_98 { get; set; }

    public string twi_99 { get; set; }

    public string twi_100 { get; set; }

    public string twi_101 { get; set; }

    public string twi_102 { get; set; }

    public string twi_103 { get; set; }

    public string twi_104 { get; set; }

    public string twi_105 { get; set; }

    public string twi_106 { get; set; }

    public string twi_107 { get; set; }

    public string twi_108 { get; set; }

    public string twi_109 { get; set; }

    public string twi_110 { get; set; }

    public string twi_111 { get; set; }

    public string twi_112 { get; set; }

    public string twi_113 { get; set; }

    public string twi_114 { get; set; }

    public string twi_115 { get; set; }

    public string twi_116 { get; set; }

    public string twi_117 { get; set; }

    public string twi_118 { get; set; }

    public string twi_119 { get; set; }

    public string twi_120 { get; set; }

    public string twi_121 { get; set; }

    public string twi_122 { get; set; }

    public string twi_123 { get; set; }

    public string twi_124 { get; set; }

    public string twi_125 { get; set; }

    public string twi_126 { get; set; }

    public string twi_127 { get; set; }

    public string twi_128 { get; set; }

    public int? twi_KtId { get; set; }

    public int? twi_KlId { get; set; }

    public int? twi_MaKorpusId { get; set; }

    public int? twi_MaFrontId { get; set; }
}