// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SGT_BRIDGE.Models;

public partial class vwPolaWlasne_Dokument
{
    public int dok_Id { get; set; }

    public int dok_Typ { get; set; }

    public int dok_Podtyp { get; set; }

    public int? dok_MagId { get; set; }

    public int? dok_Nr { get; set; }

    public string dok_NrRoz { get; set; }

    public string dok_NrPelny { get; set; }

    public string dok_NrPelnyOryg { get; set; }

    public int? dok_DoDokId { get; set; }

    public string dok_DoDokNrPelny { get; set; }

    public DateTime? dok_DoDokDataWyst { get; set; }

    public string dok_MscWyst { get; set; }

    public DateTime dok_DataWyst { get; set; }

    public DateTime dok_DataMag { get; set; }

    public DateTime? dok_DataOtrzym { get; set; }

    public int? dok_PlatnikId { get; set; }

    public int? dok_PlatnikAdreshId { get; set; }

    public int? dok_OdbiorcaId { get; set; }

    public int? dok_OdbiorcaAdreshId { get; set; }

    public int? dok_PlatId { get; set; }

    public DateTime? dok_PlatTermin { get; set; }

    public string dok_Wystawil { get; set; }

    public string dok_Odebral { get; set; }

    public int? dok_PersonelId { get; set; }

    public int? dok_CenyPoziom { get; set; }

    public int? dok_CenyTyp { get; set; }

    public decimal? dok_CenyKurs { get; set; }

    public decimal dok_CenyNarzut { get; set; }

    public decimal dok_RabatProc { get; set; }

    public decimal dok_WartUsNetto { get; set; }

    public decimal dok_WartUsBrutto { get; set; }

    public decimal dok_WartTwNetto { get; set; }

    public decimal dok_WartTwBrutto { get; set; }

    public decimal dok_WartOpZwr { get; set; }

    public decimal dok_WartOpWyd { get; set; }

    public decimal dok_WartMag { get; set; }

    public decimal dok_WartMagP { get; set; }

    public decimal dok_WartMagR { get; set; }

    public decimal dok_WartNetto { get; set; }

    public decimal dok_WartVat { get; set; }

    public decimal dok_WartBrutto { get; set; }

    public decimal? dok_KwWartosc { get; set; }

    public decimal? dok_KwGotowka { get; set; }

    public decimal? dok_KwKarta { get; set; }

    public decimal? dok_KwDoZaplaty { get; set; }

    public decimal? dok_KwKredyt { get; set; }

    public decimal? dok_KwReszta { get; set; }

    public string dok_Waluta { get; set; }

    public decimal dok_WalutaKurs { get; set; }

    public string dok_Uwagi { get; set; }

    public int? dok_KatId { get; set; }

    public string dok_Tytul { get; set; }

    public string dok_Podtytul { get; set; }

    public int dok_Status { get; set; }

    public int dok_StatusKsieg { get; set; }

    public int dok_StatusFiskal { get; set; }

    public bool dok_StatusBlok { get; set; }

    public bool dok_JestTylkoDoOdczytu { get; set; }

    public bool dok_JestRuchMag { get; set; }

    public bool dok_JestZmianaDatyDokKas { get; set; }

    public bool dok_JestHOP { get; set; }

    public bool dok_JestVatNaEksport { get; set; }

    public bool dok_JestVatAuto { get; set; }

    public int dok_Algorytm { get; set; }

    public int? dok_KartaId { get; set; }

    public int? dok_KredytId { get; set; }

    public int dok_RodzajOperacjiVat { get; set; }

    public int? dok_KodRodzajuTransakcji { get; set; }

    public int? dok_StatusEx { get; set; }

    public int? dok_ObiektGT { get; set; }

    public bool dok_Rozliczony { get; set; }

    public int? dok_RejId { get; set; }

    public DateTime? dok_TerminRealizacji { get; set; }

    public int dok_WalutaLiczbaJednostek { get; set; }

    public int? dok_WalutaRodzajKursu { get; set; }

    public DateTime? dok_WalutaDataKursu { get; set; }

    public int? dok_WalutaIdBanku { get; set; }

    public int dok_CenyLiczbaJednostek { get; set; }

    public int? dok_CenyRodzajKursu { get; set; }

    public DateTime? dok_CenyDataKursu { get; set; }

    public int? dok_CenyIdBanku { get; set; }

    public decimal? dok_KwPrzelew { get; set; }

    public decimal? dok_KwGotowkaPrzedplata { get; set; }

    public decimal? dok_KwPrzelewPrzedplata { get; set; }

    public int? dok_DefiniowalnyId { get; set; }

    public int? dok_TransakcjaId { get; set; }

    public string dok_TransakcjaSymbol { get; set; }

    public DateTime? dok_TransakcjaData { get; set; }

    public int? dok_PodsumaVatFSzk { get; set; }

    public int? dok_ZlecenieId { get; set; }

    public bool dok_NaliczajFundusze { get; set; }

    public bool? dok_PrzetworzonoZKwZD { get; set; }

    public bool? dok_VatMarza { get; set; }

    public int? dok_DstNr { get; set; }

    public string dok_DstNrRoz { get; set; }

    public string dok_DstNrPelny { get; set; }

    public int? dok_ObslugaDokDost { get; set; }

    public int? dok_AkcyzaZwolnienieId { get; set; }

    public int dok_ProceduraMarzy { get; set; }

    public bool dok_FakturaUproszczona { get; set; }

    public DateTime? dok_DataZakonczenia { get; set; }

    public bool dok_MetodaKasowa { get; set; }

    public int dok_TypNrIdentNabywcy { get; set; }

    public string dok_NrIdentNabywcy { get; set; }

    public int? dok_AdresDostawyId { get; set; }

    public int? dok_AdresDostawyAdreshId { get; set; }

    public int? dok_VenderoId { get; set; }

    public string dok_VenderoSymbol { get; set; }

    public DateTime? dok_VenderoData { get; set; }

    public int? dok_SelloId { get; set; }

    public string dok_SelloSymbol { get; set; }

    public DateTime? dok_SelloData { get; set; }

    public int? dok_TransakcjaJednolitaId { get; set; }

    public bool? dok_PodpisanoElektronicznie { get; set; }

    public string dok_UwagiExt { get; set; }

    public int? dok_VenderoStatus { get; set; }

    public bool? dok_ZaimportowanoDoEwidencjiAkcyzowej { get; set; }

    public int? dok_TermPlatStatus { get; set; }

    public string dok_TermPlatTransId { get; set; }

    public bool dok_DokumentFiskalnyDlaPodatnikaVat { get; set; }

    public bool dok_CesjaPlatnikOdbiorca { get; set; }

    public decimal dok_WartOplRecykl { get; set; }

    public int? dok_TermPlatIdKonfig { get; set; }

    public int? dok_TermPlatIdZadania { get; set; }

    public int? dok_PromoZenCardStatus { get; set; }

    public int? dok_NrRachunkuBankowegoPdm { get; set; }

    public bool dok_SzybkaPlatnosc { get; set; }

    public bool dok_MechanizmPodzielonejPlatnosci { get; set; }

    public int? dok_IdSesjiKasowej { get; set; }

    public int? pwd_Id { get; set; }

    public int? pwd_TypObiektu { get; set; }

    public int? pwd_IdObiektu { get; set; }

    public int? pwd_IdPozycji { get; set; }

    public DateTime? pwd_Data01 { get; set; }

    public DateTime? pwd_Data02 { get; set; }

    public DateTime? pwd_Data03 { get; set; }

    public DateTime? pwd_Data04 { get; set; }

    public DateTime? pwd_Data05 { get; set; }

    public DateTime? pwd_Data06 { get; set; }

    public DateTime? pwd_Data07 { get; set; }

    public DateTime? pwd_Data08 { get; set; }

    public DateTime? pwd_Data09 { get; set; }

    public DateTime? pwd_Data10 { get; set; }

    public int? pwd_Liczba01 { get; set; }

    public int? pwd_Liczba02 { get; set; }

    public int? pwd_Liczba03 { get; set; }

    public int? pwd_Liczba04 { get; set; }

    public int? pwd_Liczba05 { get; set; }

    public int? pwd_Liczba06 { get; set; }

    public int? pwd_Liczba07 { get; set; }

    public int? pwd_Liczba08 { get; set; }

    public int? pwd_Liczba09 { get; set; }

    public int? pwd_Liczba10 { get; set; }

    public string pwd_Tekst01 { get; set; }

    public string pwd_Tekst02 { get; set; }

    public string pwd_Tekst03 { get; set; }

    public string pwd_Tekst04 { get; set; }

    public string pwd_Tekst05 { get; set; }

    public string pwd_Tekst06 { get; set; }

    public string pwd_Tekst07 { get; set; }

    public string pwd_Tekst08 { get; set; }

    public string pwd_Tekst09 { get; set; }

    public string pwd_Tekst10 { get; set; }

    public decimal? pwd_Kwota01 { get; set; }

    public decimal? pwd_Kwota02 { get; set; }

    public decimal? pwd_Kwota03 { get; set; }

    public decimal? pwd_Kwota04 { get; set; }

    public decimal? pwd_Kwota05 { get; set; }

    public decimal? pwd_Kwota06 { get; set; }

    public decimal? pwd_Kwota07 { get; set; }

    public decimal? pwd_Kwota08 { get; set; }

    public decimal? pwd_Kwota09 { get; set; }

    public decimal? pwd_Kwota10 { get; set; }

    public int? pwd_Fk01 { get; set; }

    public int? pwd_Fk02 { get; set; }

    public int? pwd_Fk03 { get; set; }

    public int? pwd_Fk04 { get; set; }

    public int? pwd_Fk05 { get; set; }

    public int? pwd_Fk06 { get; set; }

    public int? pwd_Fk07 { get; set; }

    public int? pwd_Fk08 { get; set; }

    public int? pwd_Fk09 { get; set; }

    public int? pwd_Fk10 { get; set; }

    public bool? pwd_Flaga01 { get; set; }

    public bool? pwd_Flaga02 { get; set; }

    public bool? pwd_Flaga03 { get; set; }

    public bool? pwd_Flaga04 { get; set; }

    public bool? pwd_Flaga05 { get; set; }

    public bool? pwd_Flaga06 { get; set; }

    public bool? pwd_Flaga07 { get; set; }

    public bool? pwd_Flaga08 { get; set; }

    public bool? pwd_Flaga09 { get; set; }

    public bool? pwd_Flaga10 { get; set; }
}