// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SGT_BRIDGE.Models;

public partial class vwPolaWlasne_Kontrahent
{
    public int kh_Id { get; set; }

    public string kh_Symbol { get; set; }

    public int kh_Rodzaj { get; set; }

    public string kh_REGON { get; set; }

    public int? kh_IdOdbiorca { get; set; }

    public string kh_Kontakt { get; set; }

    public string kh_PESEL { get; set; }

    public string kh_NrDowodu { get; set; }

    public DateTime? kh_DataWyd { get; set; }

    public string kh_OrganWyd { get; set; }

    public bool kh_CentrumAut { get; set; }

    public bool kh_InstKredytowa { get; set; }

    public string kh_PrefKontakt { get; set; }

    public string kh_WWW { get; set; }

    public string kh_EMail { get; set; }

    public int? kh_IdGrupa { get; set; }

    public int? kh_IdFormaP { get; set; }

    public int? kh_Cena { get; set; }

    public bool kh_PlatOdroczone { get; set; }

    public bool kh_OdbDet { get; set; }

    public int? kh_IdRabat { get; set; }

    public int kh_MaxDokKred { get; set; }

    public decimal kh_MaxWartDokKred { get; set; }

    public decimal kh_MaxWartKred { get; set; }

    public int kh_MaxDniSp { get; set; }

    public string kh_NrAnalitykaD { get; set; }

    public string kh_NrAnalitykaO { get; set; }

    public string kh_Uwagi { get; set; }

    public bool kh_ZgodaDO { get; set; }

    public int? kh_IdOsobaDO { get; set; }

    public bool kh_ZgodaMark { get; set; }

    public bool kh_ZgodaEMail { get; set; }

    public bool kh_CzyKomunikat { get; set; }

    public string kh_Komunikat { get; set; }

    public bool kh_KomunikatZawsze { get; set; }

    public DateTime? kh_KomunikatOd { get; set; }

    public byte[] kh_Grafika { get; set; }

    public string kh_Pole1 { get; set; }

    public string kh_Pole2 { get; set; }

    public string kh_Pole3 { get; set; }

    public string kh_Pole4 { get; set; }

    public string kh_Pole5 { get; set; }

    public string kh_Pole6 { get; set; }

    public string kh_Pole7 { get; set; }

    public string kh_Pole8 { get; set; }

    public bool kh_Jednorazowy { get; set; }

    public string kh_Pracownik { get; set; }

    public bool kh_Zablokowany { get; set; }

    public bool kh_AdresKoresp { get; set; }

    public bool kh_UpowaznienieVAT { get; set; }

    public DateTime? kh_DataVAT { get; set; }

    public int? kh_OsobaVAT { get; set; }

    public decimal kh_ProcKarta { get; set; }

    public decimal kh_ProcKredyt { get; set; }

    public decimal kh_ProcGotowka { get; set; }

    public decimal kh_ProcPozostalo { get; set; }

    public int? kh_IdKategoriaKH { get; set; }

    public int? kh_IdEwVATSp { get; set; }

    public int kh_EwVATSpMcOdliczenia { get; set; }

    public int? kh_IdEwVATSpKateg { get; set; }

    public int? kh_IdEwVATZak { get; set; }

    public int kh_EwVATZakRodzaj { get; set; }

    public int kh_EwVATZakSposobOdliczenia { get; set; }

    public int kh_EwVATZakMcOdliczenia { get; set; }

    public int? kh_IdEwVATZakKateg { get; set; }

    public int? kh_IdRachKategPrzychod { get; set; }

    public int? kh_IdRachKategRozchod { get; set; }

    public int kh_TransakcjaVATSp { get; set; }

    public int kh_TransakcjaVATZak { get; set; }

    public bool kh_PodVATZarejestrowanyWUE { get; set; }

    public DateTime? kh_DataWaznosciVAT { get; set; }

    public string kh_OpisOperacji { get; set; }

    public bool kh_PlatPrzelew { get; set; }

    public string kh_GaduGadu { get; set; }

    public string kh_Skype { get; set; }

    public string kh_Powitanie { get; set; }

    public bool kh_AdresDostawy { get; set; }

    public int? kh_IdRodzajKontaktu { get; set; }

    public int? kh_IdPozyskany { get; set; }

    public int? kh_IdBranza { get; set; }

    public int? kh_IdRegion { get; set; }

    public int? kh_LiczbaPrac { get; set; }

    public int? kh_IdOpiekun { get; set; }

    public string kh_Imie { get; set; }

    public string kh_Nazwisko { get; set; }

    public bool kh_CRM { get; set; }

    public bool kh_Potencjalny { get; set; }

    public int? kh_IdDodal { get; set; }

    public int? kh_IdZmienil { get; set; }

    public DateTime? kh_DataDodania { get; set; }

    public DateTime? kh_DataZmiany { get; set; }

    public decimal kh_ProcPrzelew { get; set; }

    public DateTime? kh_DataOkolicznosciowa { get; set; }

    public bool kh_Osoba { get; set; }

    public int? kh_IdRachunkuWirtualnego { get; set; }

    public string kh_KRS { get; set; }

    public string kh_Domena { get; set; }

    public int kh_Akcyza { get; set; }

    public bool kh_EFakturyZgoda { get; set; }

    public DateTime? kh_EFakturyData { get; set; }

    public bool kh_MetodaKasowa { get; set; }

    public string kh_Lokalizacja { get; set; }

    public int kh_StatusAkcyza { get; set; }

    public bool kh_CzynnyPodatnikVAT { get; set; }

    public bool? kh_KorygowanieKUP { get; set; }

    public bool? kh_KorygowanieVATSp { get; set; }

    public bool? kh_KorygowanieVATZak { get; set; }

    public int kh_WzwIdFS { get; set; }

    public int kh_WzwIdWZ { get; set; }

    public int kh_WzwIdWZVAT { get; set; }

    public int kh_WzwIdZK { get; set; }

    public int kh_WzwIdZKZAL { get; set; }

    public bool kh_ZgodaNewsletterVendero { get; set; }

    public bool kh_KlientSklepuInternetowego { get; set; }

    public int kh_WzwIdZD { get; set; }

    public int kh_WzwIdCrmTransakcja { get; set; }

    public int? kh_StawkaVATPrzychod { get; set; }

    public int? kh_StawkaVATWydatek { get; set; }

    public int? kh_MalyPojazd { get; set; }

    public bool kh_StosujRabatWMultistore { get; set; }

    public int kh_CelZakupu { get; set; }

    public bool kh_StosujIndywidualnyCennikWSklepieInternetowym { get; set; }

    public bool kh_OdbiorcaCesjaPlatnosci { get; set; }

    public int? kh_IdNabywca { get; set; }

    public int? kh_IdOstatniWpisWeryfikacjiStatusuVAT { get; set; }

    public bool kh_BrakPPDlaRozrachunkowAuto { get; set; }

    public string kh_DomyslnaWaluta { get; set; }

    public int? kh_DomyslnyTypCeny { get; set; }

    public int? kh_DomyslnaTransVATSprzedaz { get; set; }

    public int? kh_DomyslnaTransVATSprzedazFW { get; set; }

    public int? kh_DomyslnaTransVATZakup { get; set; }

    public int? kh_DomyslnaTransVATZakupFW { get; set; }

    public int? kh_DomyslnyRachBankowyId { get; set; }

    public int? kh_IdOstatniWpisWeryfikacjiStatusuVIES { get; set; }

    public bool? kh_DomyslnaWalutaMode { get; set; }

    public bool? kh_DomyslnyRachBankowyIdMode { get; set; }

    public int? kh_PrzypadekSzczegolnyPIT { get; set; }

    public int? kh_WartoscNettoCzyBrutto { get; set; }

    public bool kh_StosujSzybkaPlatnosc { get; set; }

    public int? kh_IdOstatniWpisWeryfikacjiWykazPodatnikowVAT { get; set; }

    public int kh_OstrzezenieTerminPlatnosciPrzekroczony { get; set; }

    public int? pwd_Id { get; set; }

    public int? pwd_TypObiektu { get; set; }

    public int? pwd_IdObiektu { get; set; }

    public int? pwd_IdPozycji { get; set; }

    public DateTime? pwd_Data01 { get; set; }

    public DateTime? pwd_Data02 { get; set; }

    public DateTime? pwd_Data03 { get; set; }

    public DateTime? pwd_Data04 { get; set; }

    public DateTime? pwd_Data05 { get; set; }

    public DateTime? pwd_Data06 { get; set; }

    public DateTime? pwd_Data07 { get; set; }

    public DateTime? pwd_Data08 { get; set; }

    public DateTime? pwd_Data09 { get; set; }

    public DateTime? pwd_Data10 { get; set; }

    public int? pwd_Liczba01 { get; set; }

    public int? pwd_Liczba02 { get; set; }

    public int? pwd_Liczba03 { get; set; }

    public int? pwd_Liczba04 { get; set; }

    public int? pwd_Liczba05 { get; set; }

    public int? pwd_Liczba06 { get; set; }

    public int? pwd_Liczba07 { get; set; }

    public int? pwd_Liczba08 { get; set; }

    public int? pwd_Liczba09 { get; set; }

    public int? pwd_Liczba10 { get; set; }

    public string pwd_Tekst01 { get; set; }

    public string pwd_Tekst02 { get; set; }

    public string pwd_Tekst03 { get; set; }

    public string pwd_Tekst04 { get; set; }

    public string pwd_Tekst05 { get; set; }

    public string pwd_Tekst06 { get; set; }

    public string pwd_Tekst07 { get; set; }

    public string pwd_Tekst08 { get; set; }

    public string pwd_Tekst09 { get; set; }

    public string pwd_Tekst10 { get; set; }

    public decimal? pwd_Kwota01 { get; set; }

    public decimal? pwd_Kwota02 { get; set; }

    public decimal? pwd_Kwota03 { get; set; }

    public decimal? pwd_Kwota04 { get; set; }

    public decimal? pwd_Kwota05 { get; set; }

    public decimal? pwd_Kwota06 { get; set; }

    public decimal? pwd_Kwota07 { get; set; }

    public decimal? pwd_Kwota08 { get; set; }

    public decimal? pwd_Kwota09 { get; set; }

    public decimal? pwd_Kwota10 { get; set; }

    public int? pwd_Fk01 { get; set; }

    public int? pwd_Fk02 { get; set; }

    public int? pwd_Fk03 { get; set; }

    public int? pwd_Fk04 { get; set; }

    public int? pwd_Fk05 { get; set; }

    public int? pwd_Fk06 { get; set; }

    public int? pwd_Fk07 { get; set; }

    public int? pwd_Fk08 { get; set; }

    public int? pwd_Fk09 { get; set; }

    public int? pwd_Fk10 { get; set; }

    public bool? pwd_Flaga01 { get; set; }

    public bool? pwd_Flaga02 { get; set; }

    public bool? pwd_Flaga03 { get; set; }

    public bool? pwd_Flaga04 { get; set; }

    public bool? pwd_Flaga05 { get; set; }

    public bool? pwd_Flaga06 { get; set; }

    public bool? pwd_Flaga07 { get; set; }

    public bool? pwd_Flaga08 { get; set; }

    public bool? pwd_Flaga09 { get; set; }

    public bool? pwd_Flaga10 { get; set; }
}