// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SGT_BRIDGE.Models.Native;

public partial class LEO_SystemRabatowy_Zestawy
{
    public int zr_Id { get; set; }

    public string zr_Nazwa { get; set; }

    public DateTime? zr_DataOd { get; set; }

    public DateTime? zr_DataDo { get; set; }

    public int? zr_PoziomCeny { get; set; }

    public bool? zr_Aktywny { get; set; }

    public DateTime? zr_OstatniaModyfikacja { get; set; }

    public string zr_Symbol { get; set; }

    public string zr_Notatki { get; set; }

    public bool? zr_NotatkiEnabled { get; set; }

    public bool zr_DodatkowyRabatUpustKwotowyZestaw { get; set; }

    public bool zr_DodatkowyRabatUpustProcentowyZestaw { get; set; }

    public bool zr_DodatkowyRabatStalejCenyZestaw { get; set; }
}