// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SGT_BRIDGE.Models.Native;

public partial class LEO_SystemRabatowy_ZestawyGrupyKh
{
    public int? zrg_ZestawId { get; set; }

    public int? zrg_GrupaId { get; set; }
}