// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SGT_BRIDGE.Models.Native;

public partial class LEO_SystemRabatowy_ZestawyMagazyny
{
    public int zrm_ZestawId { get; set; }

    public int zrm_MagazynId { get; set; }
}