// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SGT_BRIDGE.Models.Native;

public partial class LEO_SystemRabatowy_Zbiorcze
{
    public int? zb_Typ { get; set; }

    public int? zb_ObiektId { get; set; }

    public decimal? zb_Wartosc { get; set; }
}