// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SGT_BRIDGE.Models.Native;

public partial class sl_Magazyn
{
    public int mag_Id { get; set; }

    public string mag_Symbol { get; set; }

    public string mag_Nazwa { get; set; }

    public int mag_Status { get; set; }

    public string mag_Opis { get; set; }

    public string mag_Analityka { get; set; }

    public bool mag_Glowny { get; set; }

    public bool mag_POS { get; set; }

    public Guid? mag_POSIdent { get; set; }

    public string mag_POSNazwa { get; set; }

    public string mag_POSAdres { get; set; }
}